// frontend/src/components/DeliveryBanner.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

interface Props {
  metrics?: Record<string, any> | null
}

const props = withDefaults(defineProps<Props>(), {
  metrics: null
})

const emit = defineEmits<{
  close: []
}>()

// metrics key → 用户语言（G-32：YAGNI 等黑话不上 UI）
const METRIC_LABELS: Record<string, string> = {
  lines_reduced: '少写代码',
  deps_added: '新增依赖',
  duplicates_found: '检出重复',
  readability_ok: '可读性达标',
}

const shown = ref(0)
let raf: number | null = null

const fmtValue = (key: string, v: any) => {
  if (key === 'readability_ok') return v ? '✓' : '—'
  if (typeof v === 'number') return Math.round(v)
  return v
}

onMounted(() => {
  if (!props.metrics) return
  const start = performance.now()
  const dur = 400
  function tick(now: number) {
    const p = Math.min(1, (now - start) / dur)
    shown.value = p
    if (p < 1) raf = requestAnimationFrame(tick)
  }
  raf = requestAnimationFrame(tick)
})

onUnmounted(() => {
  if (raf) cancelAnimationFrame(raf)
})
</script>

<template>
  <div v-if="metrics" class="delivery-banner" data-testid="delivery-banner">
    <div class="delivery-head">
      <span class="delivery-badge">任务完成</span>
      <button class="delivery-close" aria-label="关闭交付横幅" data-testid="delivery-close" @click="emit('close')">
        ×
      </button>
    </div>
    <p v-if="metrics.lines_reduced > 0" class="delivery-summary">
      本次少写 <b>{{ Math.round(metrics.lines_reduced * shown) }}</b> 行代码
    </p>
    <div v-if="Object.keys(metrics).length > 0" class="delivery-metrics">
      <div v-for="(v, k) in metrics" :key="k" class="delivery-metric">
        <span class="delivery-metric-label">{{ METRIC_LABELS[k] || k }}</span>
        <span class="delivery-metric-value">{{ fmtValue(k, typeof v === 'number' ? v * shown : v) }}</span>
      </div>
    </div>
    <p class="delivery-hint">在下方输入下一个任务</p>
  </div>
</template>

// frontend/src/components/DeliveryBanner.jsx
import { useEffect, useState } from 'react'

/**
 * 交付横幅（峰终定律：任务完成是关键时刻，反馈放大）
 * - 最近一次 ItemCompleted 的 metrics 展示（用户语言：L12 翻译）
 * - 数字滚动入场（多巴胺）
 * - 输入框聚焦提示"下一个任务"
 */

// metrics key → 用户语言（G-32：YAGNI 等黑话不上 UI）
const METRIC_LABELS = {
  lines_reduced: '少写代码',
  deps_added: '新增依赖',
  duplicates_found: '检出重复',
  readability_ok: '可读性达标',
}

function fmtValue(key, v) {
  if (key === 'readability_ok') return v ? '✓' : '—'
  if (typeof v === 'number') return Math.round(v)
  return v
}

export default function DeliveryBanner({ metrics, onClose }) {
  const [shown, setShown] = useState(0)

  useEffect(() => {
    if (!metrics) return
    let raf
    const target = 1
    const start = performance.now()
    const dur = 400
    function tick(now) {
      const p = Math.min(1, (now - start) / dur)
      setShown(p)
      if (p < 1) raf = requestAnimationFrame(tick)
    }
    raf = requestAnimationFrame(tick)
    return () => cancelAnimationFrame(raf)
  }, [metrics])

  if (!metrics) return null

  const entries = Object.entries(metrics)
  const saved = metrics.lines_reduced

  return (
    <div className="delivery-banner" data-testid="delivery-banner">
      <div className="delivery-head">
        <span className="delivery-badge">任务完成</span>
        <button className="delivery-close" onClick={onClose} aria-label="关闭交付横幅" data-testid="delivery-close">
          ×
        </button>
      </div>
      {saved > 0 && (
        <p className="delivery-summary">
          本次少写 <b>{Math.round(saved * shown)}</b> 行代码
        </p>
      )}
      {entries.length > 0 && (
        <div className="delivery-metrics">
          {entries.map(([k, v]) => (
            <div key={k} className="delivery-metric">
              <span className="delivery-metric-label">{METRIC_LABELS[k] || k}</span>
              <span className="delivery-metric-value">{fmtValue(k, typeof v === 'number' ? v * shown : v)}</span>
            </div>
          ))}
        </div>
      )}
      <p className="delivery-hint">在下方输入下一个任务</p>
    </div>
  )
}
