// frontend/src/components/SessionRail.jsx
import { useState } from 'react'

/**
 * 会话栏（对标 pi-web：会话列表/新建/恢复，按工作目录组织）
 * - 列表 + 事件数（未完成标记由事件数暗示）
 * - 新建会话内联输入
 * - 切换会话 = 换 JSONL 重放（事件溯源）
 */
export default function SessionRail({ sessions, activeId, onSelect, onNew }) {
  const [creating, setCreating] = useState(false)
  const [name, setName] = useState('')

  function submit() {
    const n = name.trim()
    if (!n) return
    onNew(n)
    setCreating(false)
    setName('')
  }

  return (
    <aside className="session-rail" data-testid="session-rail">
      <div className="rail-header">
        <span className="rail-title">会话</span>
        <button className="rail-new" onClick={() => setCreating((v) => !v)} aria-label="新建会话" data-testid="session-new">
          {creating ? '×' : '+'}
        </button>
      </div>
      {creating && (
        <div className="rail-create">
          <input
            className="rail-input"
            value={name}
            onChange={(e) => setName(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') submit()
            }}
            placeholder="会话名"
            autoFocus
            data-testid="session-name-input"
          />
          <button className="btn btn-primary btn-xs" onClick={submit} data-testid="session-create-ok">
            创建
          </button>
        </div>
      )}
      <div className="rail-list">
        {sessions.length === 0 && <p className="rail-empty">暂无会话</p>}
        {sessions.map((s) => (
          <button
            key={s.session_id}
            className={`rail-item ${s.session_id === activeId ? 'is-active' : ''}`}
            onClick={() => onSelect(s.session_id)}
            data-testid={`session-item-${s.session_id}`}
          >
            <span className="rail-item-name">{s.session_id}</span>
            <span className="rail-item-meta">{s.events} 条</span>
          </button>
        ))}
      </div>
    </aside>
  )
}

// frontend/src/components/SessionRail.vue
<script setup lang="ts">
import { ref } from 'vue'

interface Session {
  session_id: string
  events: number
}

interface Props {
  sessions: Session[]
  activeId?: string
}

withDefaults(defineProps<Props>(), {
  activeId: ''
})

const emit = defineEmits<{
  select: [sessionId: string]
  new: [name: string]
}>()

const creating = ref(false)
const name = ref('')

const submit = () => {
  const n = name.value.trim()
  if (!n) return
  emit('new', n)
  creating.value = false
  name.value = ''
}
</script>

<template>
  <aside class="session-rail" data-testid="session-rail">
    <div class="rail-header">
      <span class="rail-title">会话</span>
      <button class="rail-new" aria-label="新建会话" data-testid="session-new" @click="creating = !creating">
        {{ creating ? '×' : '+' }}
      </button>
    </div>
    <div v-if="creating" class="rail-create">
      <input
        v-model="name"
        class="rail-input"
        placeholder="会话名"
        autofocus
        data-testid="session-name-input"
        @keydown.enter="submit"
      />
      <button class="btn btn-primary btn-xs" data-testid="session-create-ok" @click="submit">
        创建
      </button>
    </div>
    <div class="rail-list">
      <p v-if="sessions.length === 0" class="rail-empty">暂无会话</p>
      <button
        v-for="s in sessions"
        :key="s.session_id"
        :class="['rail-item', { 'is-active': s.session_id === activeId }]"
        :data-testid="`session-item-${s.session_id}`"
        @click="emit('select', s.session_id)"
      >
        <span class="rail-item-name">{{ s.session_id }}</span>
        <span class="rail-item-meta">{{ s.events }} 条</span>
      </button>
    </div>
  </aside>
</template>
